import AppKit
import Carbon.HIToolbox

/// Inserts text by putting it on the pasteboard and sending ⌘V. By default the
/// dictation stays on the clipboard afterwards; optionally the previous contents
/// are restored. Works in nearly every app, including Electron and browsers.
enum Paster {
    /// Tag on our synthetic key events so the hotkey tap ignores them.
    static let eventTag: Int64 = 0x4D55524D // "MURM"

    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func paste(_ text: String, keepOnClipboard: Bool) {
        let pb = NSPasteboard.general
        let saved = keepOnClipboard ? nil : snapshot(pb)
        pb.clearContents()
        pb.setString(text, forType: .string)
        if !keepOnClipboard {
            // Temporary use of the clipboard: tell clipboard managers not to record it.
            pb.setString("", forType: transient)
            pb.setString("", forType: autoGenerated)
        }
        let ours = pb.changeCount
        sendKey(CGKeyCode(kVK_ANSI_V), flags: .maskCommand)
        if let saved {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) {
                guard pb.changeCount == ours else { return } // user copied something new
                pb.clearContents()
                if !saved.isEmpty { pb.writeObjects(saved) }
            }
        }
    }

    static func copy(_ text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
    }

    /// Copies the current selection via ⌘C (fallback when AX can't read it),
    /// restoring the previous clipboard afterwards.
    static func copySelection() async -> String? {
        let pb = NSPasteboard.general
        let saved = snapshot(pb)
        let before = pb.changeCount
        sendKey(CGKeyCode(kVK_ANSI_C), flags: .maskCommand)
        for _ in 0..<12 {
            try? await Task.sleep(nanoseconds: 25_000_000)
            if pb.changeCount != before { break }
        }
        guard pb.changeCount != before else { return nil }
        let text = pb.string(forType: .string)
        pb.clearContents()
        if !saved.isEmpty { pb.writeObjects(saved) }
        return text
    }

    static func sendKey(_ key: CGKeyCode, flags: CGEventFlags) {
        let src = CGEventSource(stateID: .hidSystemState)
        for down in [true, false] {
            guard let e = CGEvent(keyboardEventSource: src, virtualKey: key, keyDown: down) else { continue }
            e.flags = flags
            e.setIntegerValueField(.eventSourceUserData, value: eventTag)
            e.post(tap: .cghidEventTap)
        }
    }

    private static func snapshot(_ pb: NSPasteboard) -> [NSPasteboardItem] {
        (pb.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for t in item.types { if let d = item.data(forType: t) { copy.setData(d, forType: t) } }
            return copy
        }
    }
}
